# Generated by Django 5.2.4 on 2025-07-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'user'), (2, 'admin')], default=(1, 'user')),
        ),
    ]
