# Generated by Django 5.2.4 on 2025-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='types',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='quiz',
            name='types',
            field=models.JSONField(choices=[(1, 'multiple_choice'), (2, 'true_or_false'), (3, 'dropdown'), (4, 'numerical')], default=1),
        ),
    ]
