# Generated by Django 5.2.4 on 2025-07-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_quiz_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='types',
        ),
    ]
